### ISSUE TITLE
retry on resp.next()

### ISSUE THREAD

**Issue by gabrielsroka** [discord/access#12]
more converstaions with @somethingnew2-0

i noticed this "pattern" 4 times (paginating thru a given api)
https://github.com/discord/access/blob/7fda4989242204591dca97718ed3af4cf8582614/api/services/okta_service.py#L96-L105
don't u need to `retry` the `next()`, too?

i use async generators for it. write it once, factor it out, reuse it everywhere. something like

```py
import asyncio
from okta.client import Client as OktaClient

async def get_applications():
    async with OktaClient() as okta_client:
        filter = {'filter': 'status eq "ACTIVE"'}
        async for app in get_objects(okta_client.list_applications(filter)):
            print(f"Application Name: {app.name}")
            print(f"Application ID: {app.id}")
            async for app_user in get_objects(okta_client.list_application_users(app.id)):
                print(app_user.id)
            print()

async def get_objects(coro):
    objects, resp, _ = await coro
    while objects:
        for object in objects:
            yield object
        objects, _ = await resp.next() if resp.has_next() else (None, None)

asyncio.run(get_applications())
```

but that might not work here. i wrote it a while ago. maybe i should rewrite it

**Comment by somethingnew2-0** [comment]
Resolved in https://github.com/discord/access/pull/63
