### ISSUE TITLE
request to expose Group Active tags to Conditional Access Plugin

### ISSUE THREAD

**Issue by jonathanhle** [discord/access#37]
I'd like to make some conditional access decisions based on the tags that are applied to an Okta Group within Access.

I have an exploratory branch [here](https://github.com/discord/access/compare/main...jonathanhle:access:jle-conditional-access-redux?expand=1) if it's useful.

```
    # Auto Approve if "AutoApproval" is applied to Group
    if not access_request.request_ownership and "AutoApproval" in group_tags:
        logger.info(f"Auto-approving access request {access_request.id} to group {group.name}")
        return ConditionalAccessResponse(
            approved=True,
            reason="Group membership auto-approved based on AutoApproval tag",
            ending_at=access_request.request_ending_at,
        )
```

**Comment by somethingnew2-0** [comment]
PR to include this feature https://github.com/discord/access/pull/38
