### ISSUE TITLE
Exceptional work! 🤩

### ISSUE THREAD

**Issue by GrantBirki** [discord/access#7]
As a fellow security engineer who works on GitHub's open source IAM system ([entitlements](https://github.com/github/entitlements-app)), this is really awesome work!

**Comment by somethingnew2-0** [comment]
Thank you! Entitlements is also a great system and we definitely took a look at it for some inspiration when designing Access. 🎉

**Comment by GrantBirki** [comment]
Right back at ya! Folks on my team are checking out this project as well for inspiration into the `entitlements` system and future improvements 🎉 🤜 🤛
